var test = require('tape')
var elementClass = require('element-class')
var remove = require('./')

test('removes element', function(t) {
  var div = document.createElement('div')
  elementClass(div).add('foo')
  document.body.appendChild(div)
  remove('.foo')
  var match = document.querySelector('.foo')
  t.notOk(match)
  t.end()
})

test('removes element in scope', function(t) {
  var scope = document.createElement('div')
  var div = document.createElement('div')
  elementClass(div).add('foo')
  scope.appendChild(div)
  document.body.appendChild(scope)
  remove('.foo', scope)
  var match = document.querySelector('.foo')
  t.notOk(match)
  t.end()
})

test('removes element in multiple scopes', function(t) {
  var scopeA = document.createElement('div')
  var scopeB = document.createElement('div')
  var divA = document.createElement('div')
  var divB = document.createElement('div')
  elementClass(scopeA).add('scope')
  elementClass(scopeB).add('scope')
  elementClass(divA).add('foo')
  elementClass(divB).add('foo')
  scopeA.appendChild(divA)
  scopeB.appendChild(divB)
  document.body.appendChild(scopeA)
  document.body.appendChild(scopeB)
  remove('.foo', document.querySelectorAll('.scope'))
  var match = document.querySelector('.foo')
  t.notOk(match)
  t.end()
})